---
# We compile as the normal user (no sudo) and escalate
# only for the systemd‑unit step that touches /etc.
- name: Deploy Axiom backend
  hosts: supernanny
  gather_facts: yes
  become: false

  vars:
    user_home:    "{{ ansible_user_dir }}"
    project_root: "{{ user_home }}/SupperNanny"
    service_dir:  "{{ project_root }}/supernanny_service"
    service_bin:  "{{ service_dir }}/target/release/supernanny_service"
    env_file:     "{{ service_dir }}/.env"

  tasks:
    - name: "Step 1/3: Building Axiom backend"
      debug:
        msg: "Building SuperNanny Axiom backend with cargo..."

    - name: Build backend with cargo
      shell: |
        source $HOME/.cargo/env
        cargo build --release
      args:
        chdir: "{{ service_dir }}"
        executable: /bin/bash
        creates: "{{ service_bin }}"

    - name: "Step 2/3: Writing .env configuration"
      debug:
        msg: "Writing runtime environment variables for Axiom backend..."

    - name: Write .env file
      copy:
        dest: "{{ env_file }}"
        owner: "{{ ansible_user_id }}"
        mode: '0600'
        content: |
          DB_HOST=127.0.0.1
          DB_PORT=5432
          DB_USER=sandboxuser
          DB_PASS=supernanny
          DB_NAME=sandboxdb
          JWT_SECRET=aLmYgs2OyLXEACEzmStboJU5Rm6bC1blBdTvj9ULu8s=

    - name: "Step 3/3: Installing systemd unit"
      debug:
        msg: "Installing and enabling supernanny-axiom systemd service..."

    - name: Install systemd service
      become: true
      copy:
        dest: /etc/systemd/system/supernanny-axiom.service
        mode: '0644'
        content: |
          [Unit]
          Description=SuperNanny Axiom Server
          After=network.target postgresql.service

          [Service]
          User={{ ansible_user_id }}
          WorkingDirectory={{ service_dir }}
          ExecStart={{ service_bin }}
          EnvironmentFile={{ env_file }}
          Restart=on-failure
          NoNewPrivileges=yes
          ProtectSystem=full
          PrivateTmp=yes

          [Install]
          WantedBy=multi-user.target
      notify: restart axiom

  handlers:
    - name: restart axiom
      become: true
      systemd:
        name: supernanny-axiom
        enabled: yes
        state: restarted
        daemon_reload: yes
