---
- name: Install Rust with rustup
  hosts: all
  become: false

  tasks:
    - name: "Step 1/6: Download rustup installer"
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: '0755'

    - name: "Step 2/6: Run rustup installer (non-interactive)"
      shell: |
        /tmp/rustup-init.sh -y
      args:
        creates: ~/.cargo/bin/rustc

    - name: "Step 3/6: Ensure cargo env is sourced in .bashrc"
      lineinfile:
        path: ~/.bashrc
        line: 'source $HOME/.cargo/env'
        insertafter: EOF

    - name: Ensure cargo env is sourced in .profile
      lineinfile:
        path: ~/.profile
        line: 'source $HOME/.cargo/env'
        insertafter: EOF

    - name: "Step 4/6: Source cargo environment for this session"
      shell: bash -c "source $HOME/.cargo/env"

    - name: "Step 5/6: Check cargo version"
      shell: bash -c "source $HOME/.cargo/env && cargo --version"
      register: cargo_version_output
      changed_when: false

    - name: "Step 6/6: Show cargo version"
      debug:
        msg: "{{ cargo_version_output.stdout }}"
