- name: Install Rust with rustup
  hosts: all
  become: false
  tasks:
    - name: "Step 1/6: Download rustup installer"
      get_url:
        url: https://sh.rustup.rs
        dest: /tmp/rustup-init.sh
        mode: '0755'
    
    - name: "Step 2/6: Run rustup installer (non-interactive)"
      shell: |
        /tmp/rustup-init.sh -y
      args:
        creates: ~/.cargo/bin/rustc
    
    - name: "Step 3/6: Set default Rust toolchain to stable"
      shell: |
        PATH="$HOME/.cargo/bin:$PATH" rustup default stable
      register: rustup_default_output
      changed_when: "'unchanged' not in rustup_default_output.stdout"
    
    - name: "Step 4/6: Ensure cargo env is sourced in .bashrc"
      lineinfile:
        path: ~/.bashrc
        line: 'source $HOME/.cargo/env'
        insertafter: EOF
    
    - name: "Step 5/6: Ensure cargo env is sourced in .profile"
      lineinfile:
        path: ~/.profile
        line: 'source $HOME/.cargo/env'
        insertafter: EOF
    
    - name: "Step 6/6: Check cargo version (explicit PATH)"
      shell: |
        PATH="$HOME/.cargo/bin:$PATH" cargo --version
      register: cargo_version_output
      changed_when: false
    
    - name: "Show cargo version"
      debug:
        msg: "{{ cargo_version_output.stdout }}"
