---
- name: Install and configure Grafana
  hosts: supernanny
  become: true

  vars:
    grafana_repo: "deb [signed-by=/usr/share/keyrings/grafana.gpg] https://packages.grafana.com/oss/deb stable main"
    grafana_repo_key_url: "https://packages.grafana.com/gpg.key"
    db_host: "localhost"
    db_name: "sandboxdb"
    db_user: "sandboxuser"
    db_password: "supernanny"

  tasks:
    - name: Install APT transport and tools
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
          - gnupg2
        update_cache: yes

    - name: Download Grafana GPG key
      get_url:
        url: "{{ grafana_repo_key_url }}"
        dest: /usr/share/keyrings/grafana.gpg
        mode: '0644'

    - name: Add Grafana APT repository
      apt_repository:
        repo: "{{ grafana_repo }}"
        state: present
        filename: grafana

    - name: Install Grafana
      apt:
        name: grafana
        state: present
        update_cache: yes

    - name: Ensure Grafana is started and enabled
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Configure PostgreSQL datasource in Grafana
      copy:
        dest: /etc/grafana/provisioning/datasources/postgresql.yml
        content: |
          apiVersion: 1
          datasources:
            - name: PostgreSQL
              type: postgres
              access: proxy
              url: "{{ db_host }}:5432"
              database: "{{ db_name }}"
              user: "{{ db_user }}"
              secureJsonData:
                password: "{{ db_password }}"
              jsonData:
                sslmode: disable
                postgresVersion: 1200
                timescaledb: false
      notify: Restart Grafana

  handlers:
    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
