- name: Install and configure Grafana
  hosts: supernanny
  become: true
  vars:
    grafana_repo: "deb [signed-by=/usr/share/keyrings/grafana-archive-keyring.gpg] https://packages.grafana.com/oss/deb stable main"
    grafana_repo_key_url: "https://packages.grafana.com/gpg.key"
    db_host: "127.0.0.1"
    db_name: "sandboxdb"
    db_user: "sandboxuser"
    db_password: "supernanny"
  tasks:
    - name: Install required APT packages
      apt:
        name:
          - apt-transport-https
          - software-properties-common
          - wget
          - gnupg2
        update_cache: yes

    - name: Create keyring directory
      file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'

    - name: Download and import Grafana GPG key
      shell: |
        wget -q -O - {{ grafana_repo_key_url }} | gpg --dearmor | tee /usr/share/keyrings/grafana-archive-keyring.gpg > /dev/null
      args:
        creates: /usr/share/keyrings/grafana-archive-keyring.gpg

    - name: Add Grafana APT repository
      apt_repository:
        repo: "{{ grafana_repo }}"
        state: present
        filename: grafana

    - name: Update APT cache after adding Grafana repo
      apt:
        update_cache: yes

    - name: Install Grafana
      apt:
        name: grafana-enterprise
        state: present

    - name: Ensure Grafana service is started and enabled
      service:
        name: grafana-server
        state: started
        enabled: yes

    - name: Configure PostgreSQL datasource in Grafana
      copy:
        dest: /etc/grafana/provisioning/datasources/postgresql.yml
        content: |
          apiVersion: 1
          datasources:
            - name: PostgreSQL
              type: postgres
              access: proxy
              url: "{{ db_host }}:5432"
              database: "{{ db_name }}"
              user: "{{ db_user }}"
              secureJsonData:
                password: "{{ db_password }}"
              jsonData:
                sslmode: disable
                postgresVersion: 1200
                timescaledb: false
      notify: Restart Grafana

  handlers:
    - name: Restart Grafana
      service:
        name: grafana-server
        state: restarted
