---
# ── Play 1: Clone repository ─────────────────────────────────────────
- name: Fetch SuperNanny source
  hosts: supernanny
  gather_facts: yes
  become: false

  vars:
    repo_url: https://github.com/CODE-XANA/SupperNanny.git
    project_root: "{{ ansible_env.HOME }}/SupperNanny"

  tasks:
    - name: "Step 1/2: Ensure project directory exists"
      file:
        path: "{{ project_root }}"
        state: directory
        mode: '0755'

    - name: "Step 2/2: Clone SuperNanny Git repository"
      git:
        repo:   "{{ repo_url }}"
        dest:   "{{ project_root }}"
        depth:  1
        version: main
        update: yes
        force:  yes

# ── Remaining stack ──────────────────────────────────────────────────
- import_playbook: prepare_system.yml
- import_playbook: postgreSQL/init_postgresql.yml
- import_playbook: Rust/install_rust.yml
- import_playbook: Rust/build_sandboxer.yml
- import_playbook: Rust/deploy_axiom_server.yml
- import_playbook: Rust/deploy_admin_api.yml
- import_playbook: Rust/deploy_frontend.yml
- import_playbook: install_dev_certs.yml
