---
- name: Prepare the system
  hosts: all
  become: yes

  tasks:
    - name: Starting system preparation
      debug:
        msg: "Step 1/4: Updating APT package index..."

    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrading all packages
      debug:
        msg: "Step 2/4: Upgrading all system packages..."

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Installing git
      debug:
        msg: "Step 3/4: Ensuring git is installed..."

    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: Install Rust crate dependencies
      debug:
        msg: "Step 4/4: Installing Rust crate system dependencies (libssl-dev, pkg-config)..."

    - name: Ensure Rust build dependencies are installed
      apt:
        name:
          - pkg-config
          - libssl-dev
          - libpq-dev
          - build-essential
          - ca-certificates
          - strace
        state: present

    - name: System preparation complete
      debug:
        msg: "✅ System is updated, upgraded, and ready."
