---
- name: Prepare the system
  hosts: all
  become: yes

  tasks:
    - name: Starting system preparation
      debug:
        msg: "Step 1/3: Updating APT package index..."

    - name: Update APT package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrading all packages
      debug:
        msg: "Step 2/3: Upgrading all system packages..."

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Installing git
      debug:
        msg: "Step 3/3: Ensuring git is installed..."

    - name: Ensure git is installed
      apt:
        name: git
        state: present

    - name: System preparation complete
      debug:
        msg: "✅ System is updated, upgraded, and ready."
