
# cargo-vet config file

[cargo-vet]
version = "0.10"

[[exemptions.addr2line]]
version = "0.24.2"
criteria = "safe-to-deploy"

[[exemptions.adler2]]
version = "2.0.0"
criteria = "safe-to-deploy"

[[exemptions.aho-corasick]]
version = "1.1.3"
criteria = "safe-to-deploy"

[[exemptions.anyhow]]
version = "1.0.97"
criteria = "safe-to-deploy"

[[exemptions.async-trait]]
version = "0.1.87"
criteria = "safe-to-deploy"

[[exemptions.autocfg]]
version = "1.4.0"
criteria = "safe-to-deploy"

[[exemptions.backtrace]]
version = "0.3.74"
criteria = "safe-to-deploy"

[[exemptions.base64]]
version = "0.22.1"
criteria = "safe-to-deploy"

[[exemptions.bcrypt]]
version = "0.17.0"
criteria = "safe-to-deploy"

[[exemptions.bitflags]]
version = "2.9.0"
criteria = "safe-to-deploy"

[[exemptions.block-buffer]]
version = "0.10.4"
criteria = "safe-to-deploy"

[[exemptions.blowfish]]
version = "0.9.1"
criteria = "safe-to-deploy"

[[exemptions.bumpalo]]
version = "3.17.0"
criteria = "safe-to-deploy"

[[exemptions.byteorder]]
version = "1.5.0"
criteria = "safe-to-deploy"

[[exemptions.bytes]]
version = "1.10.1"
criteria = "safe-to-deploy"

[[exemptions.cfg-if]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.cipher]]
version = "0.4.4"
criteria = "safe-to-deploy"

[[exemptions.console]]
version = "0.15.11"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.2.17"
criteria = "safe-to-deploy"

[[exemptions.crypto-common]]
version = "0.1.6"
criteria = "safe-to-deploy"

[[exemptions.dialoguer]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.digest]]
version = "0.10.7"
criteria = "safe-to-deploy"

[[exemptions.dotenvy]]
version = "0.15.7"
criteria = "safe-to-deploy"

[[exemptions.encode_unicode]]
version = "1.0.0"
criteria = "safe-to-deploy"

[[exemptions.enumflags2]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.enumflags2_derive]]
version = "0.7.11"
criteria = "safe-to-deploy"

[[exemptions.errno]]
version = "0.3.10"
criteria = "safe-to-deploy"

[[exemptions.fallible-iterator]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.3.0"
criteria = "safe-to-deploy"

[[exemptions.futures-channel]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-core]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-macro]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-sink]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-task]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.futures-util]]
version = "0.3.31"
criteria = "safe-to-deploy"

[[exemptions.generic-array]]
version = "0.14.7"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.gimli]]
version = "0.31.1"
criteria = "safe-to-deploy"

[[exemptions.heck]]
version = "0.5.0"
criteria = "safe-to-run"

[[exemptions.hmac]]
version = "0.12.1"
criteria = "safe-to-deploy"

[[exemptions.hostname]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.inout]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.js-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.landlock]]
version = "0.4.1"
criteria = "safe-to-deploy"

[[exemptions.lazy_static]]
version = "1.5.0"
criteria = "safe-to-run"

[[exemptions.libc]]
version = "0.2.171"
criteria = "safe-to-deploy"

[[exemptions.linux-raw-sys]]
version = "0.9.2"
criteria = "safe-to-deploy"

[[exemptions.lock_api]]
version = "0.4.12"
criteria = "safe-to-deploy"

[[exemptions.log]]
version = "0.4.26"
criteria = "safe-to-deploy"

[[exemptions.md-5]]
version = "0.10.6"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.4"
criteria = "safe-to-deploy"

[[exemptions.miniz_oxide]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.mio]]
version = "1.0.3"
criteria = "safe-to-deploy"

[[exemptions.object]]
version = "0.36.7"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.3"
criteria = "safe-to-deploy"

[[exemptions.parking_lot]]
version = "0.12.3"
criteria = "safe-to-deploy"

[[exemptions.parking_lot_core]]
version = "0.9.10"
criteria = "safe-to-deploy"

[[exemptions.percent-encoding]]
version = "2.3.1"
criteria = "safe-to-deploy"

[[exemptions.phf]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.phf_shared]]
version = "0.11.3"
criteria = "safe-to-deploy"

[[exemptions.pin-project-lite]]
version = "0.2.16"
criteria = "safe-to-deploy"

[[exemptions.pin-utils]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.postgres]]
version = "0.19.10"
criteria = "safe-to-deploy"

[[exemptions.postgres-protocol]]
version = "0.6.8"
criteria = "safe-to-deploy"

[[exemptions.postgres-types]]
version = "0.2.9"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.20"
criteria = "safe-to-deploy"

[[exemptions.proc-macro2]]
version = "1.0.93"
criteria = "safe-to-deploy"

[[exemptions.quote]]
version = "1.0.38"
criteria = "safe-to-deploy"

[[exemptions.r2d2]]
version = "0.8.10"
criteria = "safe-to-deploy"

[[exemptions.r2d2_postgres]]
version = "0.18.2"
criteria = "safe-to-deploy"

[[exemptions.rand]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rand_chacha]]
version = "0.9.0"
criteria = "safe-to-deploy"

[[exemptions.rand_core]]
version = "0.9.3"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.5.10"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.11.1"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.regex-syntax]]
version = "0.8.5"
criteria = "safe-to-deploy"

[[exemptions.rustc-demangle]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.rustix]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.rustversion]]
version = "1.0.19"
criteria = "safe-to-run"

[[exemptions.scheduled-thread-pool]]
version = "0.2.7"
criteria = "safe-to-deploy"

[[exemptions.scopeguard]]
version = "1.2.0"
criteria = "safe-to-deploy"

[[exemptions.sha2]]
version = "0.10.8"
criteria = "safe-to-deploy"

[[exemptions.shell-words]]
version = "1.1.0"
criteria = "safe-to-deploy"

[[exemptions.siphasher]]
version = "1.0.1"
criteria = "safe-to-deploy"

[[exemptions.slab]]
version = "0.4.9"
criteria = "safe-to-deploy"

[[exemptions.smallvec]]
version = "1.14.0"
criteria = "safe-to-deploy"

[[exemptions.socket2]]
version = "0.5.8"
criteria = "safe-to-deploy"

[[exemptions.stringprep]]
version = "0.1.5"
criteria = "safe-to-deploy"

[[exemptions.strum]]
version = "0.27.1"
criteria = "safe-to-run"

[[exemptions.strum_macros]]
version = "0.27.1"
criteria = "safe-to-run"

[[exemptions.subtle]]
version = "2.6.1"
criteria = "safe-to-deploy"

[[exemptions.syn]]
version = "2.0.98"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.19.1"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "1.0.69"
criteria = "safe-to-deploy"

[[exemptions.thiserror-impl]]
version = "2.0.12"
criteria = "safe-to-deploy"

[[exemptions.tinyvec]]
version = "1.9.0"
criteria = "safe-to-deploy"

[[exemptions.tinyvec_macros]]
version = "0.1.1"
criteria = "safe-to-deploy"

[[exemptions.tokio]]
version = "1.44.1"
criteria = "safe-to-deploy"

[[exemptions.tokio-postgres]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.tokio-util]]
version = "0.7.13"
criteria = "safe-to-deploy"

[[exemptions.typenum]]
version = "1.18.0"
criteria = "safe-to-deploy"

[[exemptions.unicode-bidi]]
version = "0.3.18"
criteria = "safe-to-deploy"

[[exemptions.unicode-ident]]
version = "1.0.16"
criteria = "safe-to-deploy"

[[exemptions.unicode-normalization]]
version = "0.1.24"
criteria = "safe-to-deploy"

[[exemptions.unicode-properties]]
version = "0.1.3"
criteria = "safe-to-deploy"

[[exemptions.unicode-width]]
version = "0.2.0"
criteria = "safe-to-deploy"

[[exemptions.version_check]]
version = "0.9.5"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.11.0+wasi-snapshot-preview1"
criteria = "safe-to-deploy"

[[exemptions.wasi]]
version = "0.13.3+wasi-0.2.2"
criteria = "safe-to-deploy"

[[exemptions.wasite]]
version = "0.1.0"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-backend]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-macro-support]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.wasm-bindgen-shared]]
version = "0.2.100"
criteria = "safe-to-deploy"

[[exemptions.web-sys]]
version = "0.3.77"
criteria = "safe-to-deploy"

[[exemptions.whoami]]
version = "1.5.2"
criteria = "safe-to-deploy"

[[exemptions.windows]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-core]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.52.0"
criteria = "safe-to-deploy"

[[exemptions.windows-sys]]
version = "0.59.0"
criteria = "safe-to-deploy"

[[exemptions.windows-targets]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_aarch64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_i686_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnu]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_gnullvm]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.windows_x86_64_msvc]]
version = "0.52.6"
criteria = "safe-to-deploy"

[[exemptions.wit-bindgen-rt]]
version = "0.33.0"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.23"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.7.35"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.23"
criteria = "safe-to-deploy"

[[exemptions.zeroize]]
version = "1.8.1"
criteria = "safe-to-deploy"
