name: Build & Push Admin API Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  admin-api-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version tag
        id: version
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build Admin API Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/supernanny-admin-api:latest ./SuperNanny_api

      - name: Tag image with release version (if tagged)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/supernanny-admin-api:latest \
            ${{ secrets.DOCKER_USERNAME }}/supernanny-admin-api:${{ steps.version.outputs.RELEASE_TAG }}

      - name: Push Admin API image(s)
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/supernanny-admin-api:latest
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/supernanny-admin-api:${{ steps.version.outputs.RELEASE_TAG }}
          fi
