name: SuperNanny CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  rust-build:
    name: Build and audit SuperNanny components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust and tools
        run: |
          rustup update stable
          cargo install --locked trunk
          cargo install cargo-audit
      - name: Build rust-landlock-main
        working-directory: rust-landlock-main
        run: |
          cargo build --release
          cargo audit
      - name: Build SuperNanny_api
        working-directory: SuperNanny_api
        run: |
          cargo build --release
          cargo audit
      - name: Build supernanny_service
        working-directory: supernanny_service
        run: |
          cargo build --release
          cargo audit
          
      - name: Add WebAssembly target
        run: rustup target add wasm32-unknown-unknown
        
      - name: Build Yew frontend with trunk
        working-directory: SuperNanny_front/frontend
        run: trunk build --release
      - name: Build static_server
        working-directory: SuperNanny_front/static_server
        run: cargo build --release
