name: SuperNanny CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup:
    name: Setup Rust Environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install Rust and tools
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown
          cargo install --locked trunk
          cargo install cargo-audit
      # On sauvegarde l'environnement Rust pour les jobs suivants
      - name: Cache Rust environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}

  rust-landlock:
    name: Build and audit rust-landlock-main
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore Rust environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Build and audit rust-landlock-main
        working-directory: rust-landlock-main
        run: |
          cargo build --release
          cargo audit

  supernanny-api:
    name: Build and audit SuperNanny API
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore Rust environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Build and audit SuperNanny API
        working-directory: SuperNanny_api
        run: |
          cargo build --release
          cargo audit

  supernanny-service:
    name: Build and audit supernanny service
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore Rust environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Build and audit supernanny service
        working-directory: supernanny_service
        run: |
          cargo build --release
          cargo audit

  frontend:
    name: Build Yew frontend
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore Rust environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Build Yew frontend with trunk
        working-directory: SuperNanny_front/frontend
        run: trunk build --release

  static-server:
    name: Build static server
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Restore Rust environment
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.rustup
          key: ${{ runner.os }}-rust-${{ hashFiles('**/Cargo.lock') }}
      - name: Build static server
        working-directory: SuperNanny_front/static_server
        run: cargo build --release
