name: SuperNanny CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rust-build:
    name: Build and validate Rust components
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: Install trunk and cargo-audit
        run: |
          cargo install --locked trunk
          cargo install cargo-audit

      - name: Validate and build rust-landlock-main
        working-directory: rust-landlock-main
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo build --release
          cargo audit

      - name: Validate and build SuperNanny_api
        working-directory: SuperNanny_api
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo build --release
          cargo audit

      - name: Validate and build supernanny_service
        working-directory: supernanny_service
        run: |
          cargo clippy --all-targets -- -D warnings
          cargo build --release
          cargo audit

      - name: Build frontend with trunk
        working-directory: SuperNanny_front/static_server
        run: trunk build --release
