name: Build & Push Sandboxer Image

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  sandboxer-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set version tag
        id: version
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT

      - name: Build sandboxer Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:latest ./rust-landlock-main

      - name: Tag image with version (if tag triggered)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:latest \
            ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:${{ steps.version.outputs.RELEASE_TAG }}

      - name: Push image(s) to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:latest
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:${{ steps.version.outputs.RELEASE_TAG }}
          fi
