name: Build & Push Sandboxer Image
on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  sandboxer-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Set version tag
        id: version
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      
      - name: Debug project structure
        run: |
          echo "Current directory contents:"
          ls -la
          echo "rust-landlock-main directory contents:"
          ls -la ./rust-landlock-main || echo "Directory not found"
          echo "Checking for Cargo.toml:"
          find . -name "Cargo.toml"
      
      - name: Build sandboxer Docker image
        run: |
          # Determine which directory contains the Rust project
          if [ -f "./rust-landlock-main/Cargo.toml" ]; then
            PROJECT_DIR="./rust-landlock-main"
          elif [ -f "./Cargo.toml" ]; then
            PROJECT_DIR="."
          else
            # Check one level deeper
            PROJECT_DIR=$(find . -name "Cargo.toml" -not -path "*/target/*" | head -1 | xargs dirname || echo "")
            if [ -z "$PROJECT_DIR" ]; then
              echo "ERROR: Could not find Cargo.toml in repository"
              exit 1
            fi
          fi
          
          echo "Building Docker image from directory: $PROJECT_DIR"
          cd "$PROJECT_DIR"
          docker build -t ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:latest .
        
      - name: Tag image with version (if tag triggered)
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:latest \
            ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:${{ steps.version.outputs.RELEASE_TAG }}
            
      - name: Push image(s) to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:latest
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            docker push ${{ secrets.DOCKER_USERNAME }}/supernanny-sandboxer:${{ steps.version.outputs.RELEASE_TAG }}
          fi
